### ISSUE TITLE
ImmediatelyStub behaving differently than DelayedStub

### ISSUE THREAD

**Issue by fjcaetano** [Moya/Moya#422]
Ihave two requests that I concat its Observables and when I try to to stub them sending `MoyaProvider.ImmediatelySub` to te provider, the `subscribe` to the concat only receives the first request. However, if I send `MoyaProvider.DelayedStub` even with 0.1s of delay, they behave correctly.

I'm 100% sure it's an issue with the stubbing and not with our implementation because if I stop stubbing the tests (making them access the network) the code runs as expected.

I know this may be hard to reproduce and, if so, tell me and I'll try to create an example project with the steps to replay this issue.

**Comment by ashfurrow** [comment]
Yikes! Hmm, I want to make sure I understand the issue: could you post a code snippet that demonstrates what you're doing with `concat`? We can take a look at it – likely an issue from immediately stubbing means that the signal sends synchronously? Not sure, definitely need to take a look. Thanks for opening the issue!

**Comment by fjcaetano** [comment]
We have implemented a datasource for our services to paginate the HTTP responses. The datasource receives a "fetch" closure that receives an `offset` and a `limit` and must return an Observable with the request. Also, we've implemented the `subscript` method so when an element with index >= `count-5` is accessed, we try to load the next page:

``` swift
struct FriendsService {
  private let dataSource = PaginatedDataSource<[User]>(limit: 30)

  func loadFriends() -> Observable<Range<Int>> {
    dataSource.fetch = { offset, limit in
      provider.request(.Friends(APIRange(offset, limit)))
        .mapArray(User.self, rootKey: "users")
    }

    return dataSource.load()
  }
}


struct DataSource<T> {
  private(set) items = [T]()
  private let loadMore = PublishSubject<Range<Int>>()

  func load() -> Observable<Range<Int>> {
    let firstLoad = fetch(0, limit)
      .doOnNext { [weak self] items in
        self?.items = items
      }
      .map { Range(start: 0, end: $0.count) }

    return Observable.of(firstLoad, loadMore).concat()
  }

  subscript(index: Int) -> T {
    guard let index >= items.count - 5 else { return }

    fetch(items.count, limit)
      .subscribeNext { [weak self] items in
        guard let weakSelf = self else { return }

        let range = Range(start: weakSelf.items.count, end: weakSelf.items.count + items.count
        weakSelf.items += items
        weakSelf.loadMore.onNext(range)
      }
      .addDisposableTo(disposeBag)
  }
}
```

Please, notice that I've stripped down the code to the relevant parts, if you think this is confusing or something don't add up, please ask me, and I'll try to improve it.

**Comment by ashfurrow** [comment]
OK, that is a _seriously_ cool idea :100: 

To clarify, what's your test code look like? What are you expecting to happen, and what specifically is happening instead?

**Comment by fjcaetano** [comment]
Thanks @ashfurrow. This is my test:

``` swift
it("loads next page") {
  var didLoadFirstPage = false
  var didLoadNextPage = false

  _ = screen.loadFriends()
    .subscribeNext { _ in
      if !didLoadFirstPage {
        let initialCount = screen.items.count
        screen.items[initialCount - 5]

        didLoadFirstPage = true
      }
      else {
        didLoadNextPage = true
      }
    }
                
  expect(didLoadNextPage).toEventually(beTrue(), timeout: 10)
}
```

To clarify: the first element the Observable receives is the "firstLoad" from the datasource, and the following should be triggered by accessing the last elements from the array.

When we tell Moya to `StubImmediately`, the Observable only receives one element, causing `didLoadNextPage` to be false. However, without stubbing or by adding some delay, it does comply to the test and its value is true in the end..

**Comment by ashfurrow** [comment]
I think I understand your use case, not sure of the cause yet – I'll need more time to think about it. I'll try to get back to you as soon as possible.

In the meantime, you've got a workaround at lest :sweat_smile: Thanks again for filing the issue!

**Comment by ashfurrow** [comment]
Still not sure what's going on here, will try to take a look.

**Comment by scottrhoyt** [comment]
Since there hasn't been any activity on this thread for some time, I am going to go ahead and close it. Please re-open or create a new issue if you would like to discuss further. Thanks.
